spring:
  thymeleaf:
    encoding: UTF-8
    mode: HTML
    cache: false
  messages:
    basename: i18n/messages
    encoding: UTF-8
    fallback-to-system-locale: false
  datasource:
    url: jdbc:postgresql://localhost:5432/pharmacy_chain
    username: postgres
    password: z7J.6q
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
  sql:
    init:
      mode: always